version: '3.9'

services:
  web:
    container_name: web
    build: ./web
    volumes:
      - './web:/app'
      - '/app/node_modules'
    ports:
      - '3000:80'
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - api
    links:
      - api:api